[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# netlify.toml
[build]
  command = ""        # important: no build command
  publish = "."       # or "build" if your HTML files are inside /build
